# Generated by Django 3.2.9 on 2021-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
