# Generated by Django 3.2.9 on 2021-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
