# Generated by Django 3.2.9 on 2021-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viedo',
            new_name='Video',
        ),
    ]
